export interface FeatureMenuConfig {
  id: string;
  name: string;
  category: 'utama' | 'akademik' | 'komunikasi' | 'hiburan' | 'lainnya';
  categoryLabel: string;
  description: string;
  defaultMessage: string;
  defaultEstimate: string;
}

export const ADMIN_FEATURE_MENUS: FeatureMenuConfig[] = [
  {
    id: 'dashboard',
    name: 'Dashboard Ringkasan',
    category: 'utama',
    categoryLabel: 'Menu Utama',
    description: 'Statistik cepat, jadwal aktif hari ini, dan aksi kilat admin.',
    defaultMessage: 'Dashboard ringkasan sedang dalam peningkatan algoritma data.',
    defaultEstimate: 'Estimasi 15 - 30 Menit',
  },
  {
    id: 'kelas',
    name: 'Kelola Kelas & Anggota',
    category: 'utama',
    categoryLabel: 'Menu Utama',
    description: 'Manajemen kelas, kode gabung, daftar siswa, dan peran pengguna.',
    defaultMessage: 'Modul manajemen kelas & anggota sedang dalam pembaruan database.',
    defaultEstimate: 'Estimasi 30 Menit',
  },
  {
    id: 'tugas',
    name: 'Tugas & Rekap Nilai',
    category: 'akademik',
    categoryLabel: 'Akademik & Penilaian',
    description: 'Pembuatan tugas, pengumpulan dokumen, penilaian, dan ekspor nilai.',
    defaultMessage: 'Sistem pengumpulan tugas & penilaian sedang dioptimalkan.',
    defaultEstimate: 'Estimasi 20 Menit',
  },
  {
    id: 'absensi',
    name: 'Presensi & Barcode QR',
    category: 'akademik',
    categoryLabel: 'Akademik & Penilaian',
    description: 'Sesi absensi real-time, kode QR dinamis, radius GPS, dan rekap kehadiran.',
    defaultMessage: 'Server engine barcode presensi sedang dalam proses kalibrasi berkala.',
    defaultEstimate: 'Estimasi 15 Menit',
  },
  {
    id: 'bank_soal',
    name: 'Bank Soal & Ujian',
    category: 'akademik',
    categoryLabel: 'Akademik & Penilaian',
    description: 'Paket latihan soal, ujian online otomatis, dan kunci jawaban.',
    defaultMessage: 'Modul bank soal sedang dalam penyelarasan format butir ujian.',
    defaultEstimate: 'Estimasi 30 Menit',
  },
  {
    id: 'kuis_live',
    name: 'Kuis Live Interaktif',
    category: 'akademik',
    categoryLabel: 'Akademik & Penilaian',
    description: 'Kuis live real-time (Kahoot style) dengan podium juara dan leaderboard.',
    defaultMessage: 'Server websocket kuis live sedang dalam pemeliharaan kapasitas peserta.',
    defaultEstimate: 'Estimasi 20 Menit',
  },
  {
    id: 'jadwal',
    name: 'Jadwal Pelajaran',
    category: 'akademik',
    categoryLabel: 'Akademik & Penilaian',
    description: 'Jadwal mingguan mata pelajaran, ruangan, dan jam pelajaran.',
    defaultMessage: 'Modul jadwal pelajaran sedang dalam pembaruan kalender akademik.',
    defaultEstimate: 'Estimasi 15 Menit',
  },
  {
    id: 'kalender',
    name: 'Kalender Akademik',
    category: 'akademik',
    categoryLabel: 'Akademik & Penilaian',
    description: 'Kalender kegiatan sekolah, tanggal merah, dan agenda ujian.',
    defaultMessage: 'Sinkronisasi kalender akademik sedang diperbarui.',
    defaultEstimate: 'Estimasi 15 Menit',
  },
  {
    id: 'forum',
    name: 'Forum Diskusi Kelas',
    category: 'komunikasi',
    categoryLabel: 'Komunikasi & Komunitas',
    description: 'Postingan diskusi, tanya jawab, komentar, dan pengumuman kelas.',
    defaultMessage: 'Papan forum diskusi sedang dalam perapihan arsip dan moderasi pesan.',
    defaultEstimate: 'Estimasi 25 Menit',
  },
  {
    id: 'chat_siswa',
    name: 'Pesan / Chat Siswa',
    category: 'komunikasi',
    categoryLabel: 'Komunikasi & Komunitas',
    description: 'Komunikasi privat langsung antara guru/admin dengan siswa.',
    defaultMessage: 'Server pengiriman pesan siswa sedang dalam pemeliharaan enkripsi chat.',
    defaultEstimate: 'Estimasi 20 Menit',
  },
  {
    id: 'chat_owner',
    name: 'Kontak Pengembang / Owner',
    category: 'komunikasi',
    categoryLabel: 'Komunikasi & Komunitas',
    description: 'Layanan bantuan langsung ke pemilik dan developer aplikasi.',
    defaultMessage: 'Layanan kontak owner sedang melayani antrean perbaikan sistem.',
    defaultEstimate: 'Estimasi 30 Menit',
  },
  {
    id: 'anonwall',
    name: 'Dinding Anonim (AnonWall)',
    category: 'komunikasi',
    categoryLabel: 'Komunikasi & Komunitas',
    description: 'Pesan rahasia anonim siswa untuk guru atau kelas.',
    defaultMessage: 'Dinding pesan anonim sedang dalam pemfilteran keamanan konten.',
    defaultEstimate: 'Estimasi 15 Menit',
  },
  {
    id: 'moderasi',
    name: 'Moderasi Konten & Pesan',
    category: 'komunikasi',
    categoryLabel: 'Komunikasi & Komunitas',
    description: 'Panel sensor kata kasar dan persetujuan postingan siswa.',
    defaultMessage: 'Engine filter moderasi sedang diperbarui dengan kamus keamanan baru.',
    defaultEstimate: 'Estimasi 20 Menit',
  },
  {
    id: 'spin',
    name: 'Roda Keberuntungan / Spin',
    category: 'hiburan',
    categoryLabel: 'Alat & Hiburan',
    description: 'Alat acak nama siswa untuk giliran menjawab pertanyaan.',
    defaultMessage: 'Fitur roda putar siswa sedang dalam penyesuaian animasi visual.',
    defaultEstimate: 'Estimasi 15 Menit',
  },
  {
    id: 'statistik',
    name: 'Statistik & Analisis Kelas',
    category: 'lainnya',
    categoryLabel: 'Alat & Utilitas',
    description: 'Grafik performa siswa, rekap ketuntasan, dan laporan aktivitas.',
    defaultMessage: 'Kalkulasi data analitik kelas sedang dalam proses regenerasi tabel.',
    defaultEstimate: 'Estimasi 30 Menit',
  },
  {
    id: 'donasi',
    name: 'Dukungan & Donasi Kreator',
    category: 'lainnya',
    categoryLabel: 'Alat & Utilitas',
    description: 'Informasi saweria/donasi pengembang dan QRIS donasi.',
    defaultMessage: 'Gerbang donasi & apresiasi kreator sedang dalam pembaruan tautan.',
    defaultEstimate: 'Estimasi 15 Menit',
  },
  {
    id: 'saran',
    name: 'Kotak Saran & Masukan',
    category: 'lainnya',
    categoryLabel: 'Alat & Utilitas',
    description: 'Rekap masukan, kritik, dan ide fitur dari pengguna.',
    defaultMessage: 'Kotak saran pengguna sedang dalam pengarsipan laporan masuk.',
    defaultEstimate: 'Estimasi 15 Menit',
  },
  {
    id: 'pengaturan',
    name: 'Pengaturan Kelas & Profil',
    category: 'lainnya',
    categoryLabel: 'Alat & Utilitas',
    description: 'Pengaturan profil admin, tema aplikasi, dan parameter kelas.',
    defaultMessage: 'Panel pengaturan sedang dalam penyelarasan preferensi akun.',
    defaultEstimate: 'Estimasi 20 Menit',
  },
];

export const MEMBER_FEATURE_MENUS: FeatureMenuConfig[] = [
  {
    id: 'dashboard',
    name: 'Beranda & Jadwal Hari Ini',
    category: 'utama',
    categoryLabel: 'Menu Utama',
    description: 'Beranda siswa, mata pelajaran hari ini, dan pengingat tugas mendesak.',
    defaultMessage: 'Beranda siswa sedang dalam pembaruan tampilan dan optimalisasi feed.',
    defaultEstimate: 'Estimasi 15 - 30 Menit',
  },
  {
    id: 'tugas',
    name: 'Tugas Kelas & Kumpul Tugas',
    category: 'akademik',
    categoryLabel: 'Akademik & Pembelajaran',
    description: 'Daftar tugas pekerjaan rumah, unggah file tugas, dan riwayat nilai.',
    defaultMessage: 'Modul pengumpulan tugas sedang dalam peningkatan kapasitas penyimpanan file.',
    defaultEstimate: 'Estimasi 20 Menit',
  },
  {
    id: 'absensi',
    name: 'Absensi Mandiri / Scan QR',
    category: 'akademik',
    categoryLabel: 'Akademik & Pembelajaran',
    description: 'Scan kamera QR code presensi dan pengajuan izin sakit bersurat.',
    defaultMessage: 'Server verifikasi scanner presensi siswa sedang dalam pemeliharaan.',
    defaultEstimate: 'Estimasi 15 Menit',
  },
  {
    id: 'bank_soal',
    name: 'Latihan Soal & Ujian Mandiri',
    category: 'akademik',
    categoryLabel: 'Akademik & Pembelajaran',
    description: 'Latihan soal pilihan ganda & essay serta perolehan skor instan.',
    defaultMessage: 'Bank latihan soal sedang dalam penyusunan materi dan uji coba jawaban.',
    defaultEstimate: 'Estimasi 30 Menit',
  },
  {
    id: 'kuis_live',
    name: 'Kuis Live Interaktif',
    category: 'akademik',
    categoryLabel: 'Akademik & Pembelajaran',
    description: 'Masuk arena kuis live bersama guru dan bersaing di podium juara kelas.',
    defaultMessage: 'Arena kuis live sedang dalam pemeliharaan server real-time.',
    defaultEstimate: 'Estimasi 20 Menit',
  },
  {
    id: 'jadwal',
    name: 'Jadwal Pelajaran Lengkap',
    category: 'akademik',
    categoryLabel: 'Akademik & Pembelajaran',
    description: 'Jadwal belajar mingguan Senin sampai Minggu.',
    defaultMessage: 'Sinkronisasi jadwal pelajaran siswa sedang diselaraskan dengan kelas.',
    defaultEstimate: 'Estimasi 15 Menit',
  },
  {
    id: 'kalender',
    name: 'Kalender Akademik',
    category: 'akademik',
    categoryLabel: 'Akademik & Pembelajaran',
    description: 'Kalender kegiatan sekolah dan tanggal penting.',
    defaultMessage: 'Kalender akademik siswa sedang dalam pembaruan agenda semester.',
    defaultEstimate: 'Estimasi 15 Menit',
  },
  {
    id: 'forum',
    name: 'Forum Komunitas & Tanya Guru',
    category: 'komunikasi',
    categoryLabel: 'Komunikasi & Komunitas',
    description: 'Diskusi tanya jawab materi pelajaran dan berbagi wawasan antar teman.',
    defaultMessage: 'Forum komunitas siswa sedang dibersihkan dan ditingkatkan performanya.',
    defaultEstimate: 'Estimasi 20 Menit',
  },
  {
    id: 'chat_admin',
    name: 'Chat dengan Guru / Admin',
    category: 'komunikasi',
    categoryLabel: 'Komunikasi & Komunitas',
    description: 'Pesan langsung ke guru pembimbing atau wali kelas.',
    defaultMessage: 'Layanan chat guru sedang dalam pemeliharaan server pesan kilat.',
    defaultEstimate: 'Estimasi 20 Menit',
  },
  {
    id: 'chat_owner',
    name: 'Hubungi Pengembang / Owner',
    category: 'komunikasi',
    categoryLabel: 'Komunikasi & Komunitas',
    description: 'Kontak langsung ke pengembang jika mengalami masalah akun.',
    defaultMessage: 'Layanan bantuan owner sedang dalam pemeliharaan berkala.',
    defaultEstimate: 'Estimasi 30 Menit',
  },
  {
    id: 'anonwall',
    name: 'Dinding Pesan Anonim (AnonWall)',
    category: 'komunikasi',
    categoryLabel: 'Komunikasi & Komunitas',
    description: 'Kirim curhat atau apresiasi secara anonim tanpa diketahui identitasnya.',
    defaultMessage: 'Dinding pesan anonim sedang dalam moderasi keamanan dan filter kata.',
    defaultEstimate: 'Estimasi 15 Menit',
  },
  {
    id: 'ai_tutor',
    name: 'AI Assistant / Tutor Cerdas',
    category: 'hiburan',
    categoryLabel: 'Alat Bantu & AI',
    description: 'Tutor belajar cerdas berbasis AI untuk menjawab pertanyaan pelajaran 24/7.',
    defaultMessage: 'AI Assistant sedang dalam tahap pengembangan model belajar terbaik untuk Anda.',
    defaultEstimate: 'Segera hadir dalam pembaruan berikutnya',
  },
  {
    id: 'fokus',
    name: 'Alat Belajar Fokus (Pomodoro)',
    category: 'hiburan',
    categoryLabel: 'Alat Bantu & AI',
    description: 'Timer belajar konsentrasi tinggi dengan suara ambient dan catatan fokus.',
    defaultMessage: 'Modul timer fokus belajar sedang dalam penyempurnaan audio ambient.',
    defaultEstimate: 'Estimasi 15 Menit',
  },
  {
    id: 'game',
    name: 'Mini Games Edukasi',
    category: 'hiburan',
    categoryLabel: 'Hiburan Edukasi',
    description: 'Permainan edukatif pengasah otak santai setelah belajar.',
    defaultMessage: 'Wahana game edukasi sedang dalam pembaruan level tantangan baru.',
    defaultEstimate: 'Estimasi 25 Menit',
  },
  {
    id: 'pet',
    name: 'Virtual Study Pet (Teman Belajar)',
    category: 'hiburan',
    categoryLabel: 'Hiburan Edukasi',
    description: 'Peliharaan virtual yang tumbuh seiring konsistensi belajar siswa.',
    defaultMessage: 'Teman belajar virtual sedang istirahat untuk pembaruan fitur pakan & exp.',
    defaultEstimate: 'Estimasi 20 Menit',
  },
  {
    id: 'statistik',
    name: 'Statistik Belajar Pribadi',
    category: 'lainnya',
    categoryLabel: 'Lainnya',
    description: 'Grafik absensi pribadi, ketuntasan tugas, dan lencana pencapaian.',
    defaultMessage: 'Kalkulator statistik belajar pribadi sedang dalam rekalkulasi otomatis.',
    defaultEstimate: 'Estimasi 15 Menit',
  },
  {
    id: 'creator',
    name: 'Dukungan Kreator / Donasi',
    category: 'lainnya',
    categoryLabel: 'Lainnya',
    description: 'Dukung pengembangan aplikasi ini dengan donasi sukarela.',
    defaultMessage: 'Halaman apresiasi kreator sedang dalam pembaruan informasi saweria.',
    defaultEstimate: 'Estimasi 15 Menit',
  },
  {
    id: 'saran',
    name: 'Kotak Saran & Masukan',
    category: 'lainnya',
    categoryLabel: 'Lainnya',
    description: 'Sampaikan saran dan masukan untuk aplikasi yang lebih baik.',
    defaultMessage: 'Kotak saran siswa sedang dalam peninjauan berkala oleh tim.',
    defaultEstimate: 'Estimasi 15 Menit',
  },
  {
    id: 'setting',
    name: 'Pengaturan Akun & Tampilan',
    category: 'lainnya',
    categoryLabel: 'Lainnya',
    description: 'Ubah tema, informasi profil siswa, dan preferensi notifikasi.',
    defaultMessage: 'Menu pengaturan akun siswa sedang dalam sinkronisasi cloud.',
    defaultEstimate: 'Estimasi 20 Menit',
  },
];

export const getAdminFeatureConfig = (id: string): FeatureMenuConfig | undefined => {
  return ADMIN_FEATURE_MENUS.find((f) => f.id === id);
};

export const getMemberFeatureConfig = (id: string): FeatureMenuConfig | undefined => {
  return MEMBER_FEATURE_MENUS.find((f) => f.id === id);
};
